USE ibitur_db;


DROP TABLE IF EXISTS TravelRoute;
DROP TABLE IF EXISTS TripEvent;
DROP TABLE IF EXISTS Accommodation;
DROP TABLE IF EXISTS Hotel;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS TourDay;
DROP TABLE IF EXISTS TourTags;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS TourCancel;
DROP TABLE IF EXISTS IncludedDependents;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Tour;
DROP TABLE IF EXISTS CustomerTelephones;
DROP TABLE IF EXISTS CustomerPromotionCards;
DROP TABLE IF EXISTS PromotionCard;
DROP TABLE IF EXISTS Dependent;
DROP TABLE IF EXISTS CustomerAccount;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS StaffAccount;
DROP TABLE IF EXISTS Account;
